### PR TITLE
Fixed virtual terminal input sequence parsing

### LINKED ISSUE #2: Modifier keys and special keys are not handled correctly
As noted by others, function keys are not recognized properly.
Nor are holding modifier keys while pressing another key.
'BackTab' is not recognized (Shift + Tab).

All of the keyboard input data is available in the response to the ReadConsoleInputW.
However, the way it is processed, some data is ignored and some is just processed incorrectly.

Possible solutions:
- Improve handleInputEvent function such that keypresses that include special chars and/or modifier keys are processed immediately and pushed onto the eventChannel. This avoids the extra step of pushing bytes into the byte buffer, which has the problem that some keypresses don't have an easy way to translate into a byte sequence that can be interpreted correctly later on.
- Invent unique byte sequences that can unabiguously specify special char and modifier char sequences.

### PR DESCRIPTION
**Pull request by chhackett**
There were numerous errors and inconsistencies in the way input sequences were parsed, which have now been fixed.
UTF8 initialization was removed - not necessary for Windows.
And finally, Windows UTF16 input processing code was cleaned up.

### CODE REVIEW

File: src/Graphics/Vty/Platform/Windows/WindowsInterfaces.hs [hunk 1]
```diff
@@ -45,36 +45,38 @@ readBuf' eventChannel inputEventPtr handle bufferPtr maxInputRecords = do
...
-                let utf8Char = encodeChar $ toEnum charVal
-                writeToBuffer utf8Char offset
-                return (offset + length utf8Char, Nothing)
+            else encodeAndWriteToBuf offset charVal
+            where
+                isSurrogate :: Int -> Bool
+                isSurrogate c = 0xD800 <= c && c < 0xDC00
         processCWChar (offset, Just surogateVal) charVal = do
-            let utf8Char = encodeChar $ toEnum $ (((surogateVal .&. 0x3FF) `shiftL` 10) .|. (charVal .&. 0x3FF)) + 0x10000
+            let utf8Char = toEnum $ (((surogateVal .&. 0x3FF) `shiftL` 10) .|. (charVal .&. 0x3FF)) + 0x10000
```
Comment (chhackett) [inline src/Graphics/Vty/Platform/Windows/WindowsInterfaces.hs]: This is wrong... Using toEnum twice? I suppose it doesn't break anything at least, but it's bad.
